pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat '''
                cd Documents\\workspace-spring-tools-for-eclipse-4.32.0.RELEASE\\zzz
                mvnw.cmd clean package
                '''
            }
        }
    }
}
